"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import { useAuth } from "@/components/auth-provider";
import { api } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

export default function RegisterPage() {
  const { register } = useAuth();
  const router = useRouter();
  const [busy, setBusy] = useState(false);
  const [credentials, setCredentials] = useState<{ memberCode: string; password: string } | null>(
    null,
  );
  const [form, setForm] = useState({
    name: "",
    phone: "",
    panNumber: "",
    pinCode: "",
    sponsorCode: "",
  });

  useEffect(() => {
    api<{ needsSetup: boolean }>("/public/status")
      .then((s) => {
        if (s.needsSetup) router.replace("/setup");
      })
      .catch(() => {});
  }, [router]);

  async function onSubmit(e: FormEvent) {
    e.preventDefault();
    setBusy(true);
    try {
      const result = await register({
        name: form.name,
        phone: form.phone,
        panNumber: form.panNumber,
        pinCode: form.pinCode || undefined,
        sponsorCode: form.sponsorCode || undefined,
      });
      setCredentials(result.credentials);
      toast.success("Account created. Save your Member ID and password now.");
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Could not register");
    } finally {
      setBusy(false);
    }
  }

  if (credentials) {
    return (
      <div className="mx-auto flex max-w-md flex-col gap-6 px-4 py-16">
        <div>
          <h1 className="font-heading text-3xl font-semibold">Save your login</h1>
          <p className="mt-2 text-sm text-muted-foreground">
            These credentials are generated by the system and shown once here. Copy them before you
            continue. Admin can also see the password until you sign in the first time.
          </p>
        </div>
        <Card>
          <CardHeader>
            <CardTitle>Your credentials</CardTitle>
          </CardHeader>
          <CardContent className="space-y-3">
            <p>
              Member ID: <span className="font-mono font-medium">{credentials.memberCode}</span>
            </p>
            <p>
              Password: <span className="font-mono font-medium">{credentials.password}</span>
            </p>
            <Button className="w-full" onClick={() => router.push("/dashboard")}>
              Continue to dashboard
            </Button>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className="mx-auto flex max-w-md flex-col gap-6 px-4 py-16">
      <div>
        <h1 className="font-heading text-3xl font-semibold">Become a distributor</h1>
        <p className="mt-2 text-sm text-muted-foreground">
          PAN is mandatory. You do not choose a password — we issue a Member ID and password after
          signup. Optionally enter a PIN instead of paying the joining fee later.
        </p>
      </div>
      <Card>
        <CardHeader>
          <CardTitle>Registration</CardTitle>
        </CardHeader>
        <CardContent>
          <form className="space-y-4" onSubmit={onSubmit}>
            <Field label="Full name" value={form.name} onChange={(name) => setForm({ ...form, name })} />
            <Field
              label="10-digit phone"
              value={form.phone}
              onChange={(phone) => setForm({ ...form, phone })}
            />
            <Field
              label="PAN number"
              value={form.panNumber}
              onChange={(panNumber) => setForm({ ...form, panNumber: panNumber.toUpperCase() })}
            />
            <Field
              label="Sponsor Member ID (optional)"
              value={form.sponsorCode}
              onChange={(sponsorCode) => setForm({ ...form, sponsorCode: sponsorCode.toUpperCase() })}
              required={false}
            />
            <Field
              label="PIN code (optional)"
              value={form.pinCode}
              onChange={(pinCode) => setForm({ ...form, pinCode })}
              required={false}
            />
            <Button type="submit" className="w-full" disabled={busy}>
              {busy ? "Creating account…" : "Create account"}
            </Button>
          </form>
        </CardContent>
      </Card>
      <p className="text-sm text-muted-foreground">
        Already registered?{" "}
        <Link href="/login" className="text-primary">
          Sign in with Member ID
        </Link>
      </p>
    </div>
  );
}

function Field({
  label,
  value,
  onChange,
  type = "text",
  required = true,
}: {
  label: string;
  value: string;
  onChange: (v: string) => void;
  type?: string;
  required?: boolean;
}) {
  const id = label.toLowerCase().replaceAll(" ", "-");
  return (
    <div className="space-y-2">
      <Label htmlFor={id}>{label}</Label>
      <Input
        id={id}
        type={type}
        value={value}
        onChange={(e) => onChange(e.target.value)}
        required={required}
      />
    </div>
  );
}
