"use client";

import { useEffect, useState } from "react";
import { toast } from "sonner";
import { RequireAuth } from "@/components/require-auth";
import { PageHero, PageShell } from "@/components/page-shell";
import { api } from "@/lib/api";
import { inr } from "@/lib/money";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

type TeamSummary = {
  weeklyPayouts: {
    id: string;
    weekStart: string;
    weekEnd: string;
    generatedAmount: number;
    downlineTotal: number;
    status: string;
    adminNote: string | null;
  }[];
};

export default function IncomeSlipPage() {
  return (
    <RequireAuth>
      <Inner />
    </RequireAuth>
  );
}

function Inner() {
  const [team, setTeam] = useState<TeamSummary | null>(null);

  useEffect(() => {
    api<TeamSummary>("/member/team")
      .then(setTeam)
      .catch((err) => toast.error(err.message));
  }, []);

  if (!team) {
    return <p className="px-4 py-16 text-center text-muted-foreground">Loading income slips…</p>;
  }

  return (
    <PageShell width="6xl" className="space-y-6">
      <PageHero
        title="Income Slip"
        description="Weekly payout reports generated by admin. Approved slips are paid to your bank account."
      />
      <Card>
        <CardHeader>
          <CardTitle>Weekly payout slips</CardTitle>
        </CardHeader>
        <CardContent>
          {team.weeklyPayouts.length === 0 ? (
            <p className="text-sm text-muted-foreground">
              No weekly reports yet. After matching runs, admin generates payout reports and approves them.
            </p>
          ) : (
            <ul className="space-y-3 text-sm">
              {team.weeklyPayouts.map((row) => (
                <li key={row.id} className="rounded-lg border p-4">
                  <div className="flex flex-wrap items-start justify-between gap-3">
                    <div>
                      <p className="font-medium">
                        {row.weekStart} → {row.weekEnd}
                      </p>
                      <p className="text-muted-foreground">
                        Generated {inr(row.generatedAmount)} · {row.downlineTotal} in team
                      </p>
                    </div>
                    <Badge variant={row.status === "APPROVED" ? "default" : "secondary"}>
                      {row.status.replaceAll("_", " ")}
                    </Badge>
                  </div>
                  {row.adminNote ? <p className="mt-2 text-muted-foreground">Admin: {row.adminNote}</p> : null}
                </li>
              ))}
            </ul>
          )}
        </CardContent>
      </Card>
    </PageShell>
  );
}
